### ISSUE TITLE
How to fix?

### ISSUE THREAD

**Issue by PanelSerwerson** [bear-codes/Harbor#5]
![obraz](https://github.com/RealTriassic/Harbor/assets/111978684/a6ddc615-fd77-42af-806e-69d79cc4daf6)
I'm running python on ptero

**Comment by RealTriassic** [comment]
What hosting service are you running this on?

**Comment by PanelSerwerson** [comment]
> What hosting service are you running this on?

nerozix-hosting.fr

**Comment by RealTriassic** [comment]
I am not familiar with this hosting service.

Are you using the Python wrapper to run Harbor?

**Comment by PanelSerwerson** [comment]
> 

Yes. I'm installed python wrapper and harbor.sh

**Comment by RealTriassic** [comment]
Can you take a screenshot of your file manager contents?

Also go into /usr/local/bin and take a screenshot of that.

**Comment by PanelSerwerson** [comment]
Nevermind, I fix that

**Comment by RealTriassic** [comment]
> Nevermind, I fix that

How did you fix it?
