### ISSUE TITLE
harbor.sh: 104: /home/container/usr/local/bin/proot: not found

### ISSUE THREAD

**Issue by Crazys-Corner** [bear-codes/Harbor#6]
How to fix? 

I am using Python

Hosted off of my own Ptero install, so let me know if I need to change any settings to make this work. 

![image](https://github.com/RealTriassic/Harbor/assets/97609827/184c7c4d-730d-4780-b131-1a0bad358714)

**Comment by RealTriassic** [comment]
> How to fix?
> 
> I am using Python
> 
> Hosted off of my own Ptero install, so let me know if I need to change any settings to make this work.
> 
> ![image](https://user-images.githubusercontent.com/97609827/257003996-184c7c4d-730d-4780-b131-1a0bad358714.png)

I have noticed multiple people having issues with the Python wrapper.. I am going to be looking into this soon

**Comment by MxrkUnderflow** [comment]
the NodeJS wrapper also has the same problem
![image](https://github.com/RealTriassic/Harbor/assets/128064869/96b1d846-06e6-4985-8655-dcce1309bcf5)

**Comment by tristanpoland** [comment]
Just had this same issue

**Comment by RealTriassic** [comment]
I believe I rectified the issue in the commit https://github.com/RealTriassic/Harbor/commit/fd00de29d53d61359822f82e7ccae0029b3a6703.

Retry by deleting the harbor.sh and .installed files and run one of the wrappers.

**Comment by RealTriassic** [comment]
I'm going to close the issue, but feel free to reopen it if the issue persists, thanks.
