### ISSUE TITLE
proot error

### ISSUE THREAD

**Issue by DasEric** [bear-codes/Harbor#8]
when i run the script it gives me an error, i dont know what to do, proot is installed look at the attached screenshot
![Screenshot_6](https://github.com/RealTriassic/Harbor/assets/60920916/c0087f45-6c6e-4b92-9d3c-357180e71674)

**Comment by RealTriassic** [comment]
Interesting, proot seems to have failed to download. Can you try opening the `harbor.sh` file and remove `clear &&` from line 71? Then remove the `.installed` file from your server's root directory and then try start the server, copy the console output and send it here.

**Comment by DasEric** [comment]
okay, thanks and here: 
![Screenshot_6](https://github.com/RealTriassic/Harbor/assets/60920916/e4b02937-637e-401e-a2ab-0f203a662957)

**Comment by RealTriassic** [comment]
Oh, it appears that you're not running Harbor under a Pterodactyl server. Typically Pterodactyl would place your files in /home/container, but in your environment that isn't the case. Currently Harbor only supports Pterodactyl servers, although support for running outside of Pterodactyl servers may be added in the future.
